# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import logging
from PyQt5 import QtCore, QtGui, QtWidgets

	


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        logging.basicConfig(level=logging.INFO)
        logging.info('Bienvenido')
        logging.info('Aplicación iniciada correctamente')
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1204, 820)
        MainWindow.setStyleSheet("background-color:#FFCC99")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1191, 791))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(740, 440, 81, 81))
        self.label_4.setStyleSheet("background-color:none;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../news.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_4.setGeometry(QtCore.QRect(710, 420, 341, 121))
        self.pushButton_4.setMinimumSize(QtCore.QSize(329, 0))
        self.pushButton_4.setStyleSheet("border-color: black;\n"
"border-width: 4px;\n"
"background-color: #99FF99;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 800;\n"
"font-size: 35px;\n"
"text-align: right;\n"
"padding-right: 20px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 420, 341, 121))
        self.pushButton_2.setMinimumSize(QtCore.QSize(329, 0))
        self.pushButton_2.setStyleSheet("#pushButton_2 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #FF6666;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 800;\n"
"font-size: 28px;\n"
"text-align: right;\n"
"padding-right: 16px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(170, 200, 111, 101))
        self.label_2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.label_2.setStyleSheet("background-color: none;")
        self.label_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../trofeo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(-2)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(490, 70, 231, 81))
        self.label_5.setStyleSheet("background-color: none;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../title_logo.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setGeometry(QtCore.QRect(730, 210, 81, 71))
        self.label.setStyleSheet("background-color: none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../MDLR.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(710, 190, 341, 121))
        self.pushButton_3.setMinimumSize(QtCore.QSize(329, 0))
        self.pushButton_3.setStyleSheet("#pushButton_3 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #66CCCC;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 26px;\n"
"text-align: right;\n"
"padding-right: 10px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(170, 450, 81, 71))
        self.label_3.setStyleSheet("background-color:none;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../mic.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(490, 280, 211, 191))
        self.label_6.setStyleSheet("background-color:none;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../mainLogo.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        self.pushButton.setGeometry(QtCore.QRect(150, 190, 341, 121))
        self.pushButton.setMinimumSize(QtCore.QSize(329, 0))
        self.pushButton.setStyleSheet("#pushButton {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #FFCC00;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 35px;\n"
"text-align: right;\n"
"padding-right: 20px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4.raise_()
        self.pushButton_3.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.stackedWidget.addWidget(self.page_3)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.pushButton_17 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_17.setGeometry(QtCore.QRect(20, 330, 181, 61))
        self.pushButton_17.setStyleSheet("#pushButton_17 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #FF6666;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"}\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_88 = QtWidgets.QLabel(self.page_7)
        self.label_88.setGeometry(QtCore.QRect(880, 200, 5, 581))
        self.label_88.setStyleSheet("background-color: black;")
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.page_7)
        self.label_89.setGeometry(QtCore.QRect(580, 680, 231, 31))
        self.label_89.setStyleSheet("background-color: white;")
        self.label_89.setText("")
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.page_7)
        self.label_90.setGeometry(QtCore.QRect(580, 270, 231, 31))
        self.label_90.setStyleSheet("background-color: white;")
        self.label_90.setText("")
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.page_7)
        self.label_91.setGeometry(QtCore.QRect(580, 730, 231, 31))
        self.label_91.setStyleSheet("background-color: white;")
        self.label_91.setText("")
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.page_7)
        self.label_92.setGeometry(QtCore.QRect(270, 340, 856, 5))
        self.label_92.setStyleSheet("background-color: black;")
        self.label_92.setObjectName("label_92")
        self.label_93 = QtWidgets.QLabel(self.page_7)
        self.label_93.setGeometry(QtCore.QRect(340, 380, 81, 71))
        self.label_93.setText("")
        self.label_93.setPixmap(QtGui.QPixmap("../Fulls/fotos/icono2.png"))
        self.label_93.setScaledContents(True)
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(self.page_7)
        self.label_94.setGeometry(QtCore.QRect(340, 240, 81, 71))
        self.label_94.setText("")
        self.label_94.setPixmap(QtGui.QPixmap("../Fulls/fotos/icono1.png"))
        self.label_94.setScaledContents(True)
        self.label_94.setObjectName("label_94")
        self.label_95 = QtWidgets.QLabel(self.page_7)
        self.label_95.setGeometry(QtCore.QRect(270, 490, 856, 5))
        self.label_95.setStyleSheet("background-color: black;")
        self.label_95.setObjectName("label_95")
        self.label_96 = QtWidgets.QLabel(self.page_7)
        self.label_96.setGeometry(QtCore.QRect(340, 690, 81, 71))
        self.label_96.setText("")
        self.label_96.setPixmap(QtGui.QPixmap("../Fulls/fotos/icono4.png"))
        self.label_96.setScaledContents(True)
        self.label_96.setObjectName("label_96")
        self.label_97 = QtWidgets.QLabel(self.page_7)
        self.label_97.setGeometry(QtCore.QRect(580, 430, 231, 31))
        self.label_97.setStyleSheet("background-color: white;")
        self.label_97.setText("")
        self.label_97.setObjectName("label_97")
        self.pushButton_18 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_18.setGeometry(QtCore.QRect(940, 540, 111, 41))
        self.pushButton_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_18.setStyleSheet("background-color: silver;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_98 = QtWidgets.QLabel(self.page_7)
        self.label_98.setGeometry(QtCore.QRect(580, 580, 231, 31))
        self.label_98.setStyleSheet("background-color: white;")
        self.label_98.setText("")
        self.label_98.setObjectName("label_98")
        self.pushButton_19 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_19.setGeometry(QtCore.QRect(20, 190, 181, 61))
        self.pushButton_19.setStyleSheet("#pushButton_19 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #FFCC00;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_99 = QtWidgets.QLabel(self.page_7)
        self.label_99.setGeometry(QtCore.QRect(580, 220, 231, 31))
        self.label_99.setStyleSheet("background-color: white;")
        self.label_99.setText("")
        self.label_99.setObjectName("label_99")
        self.label_100 = QtWidgets.QLabel(self.page_7)
        self.label_100.setGeometry(QtCore.QRect(520, 200, 5, 581))
        self.label_100.setStyleSheet("background-color: black;")
        self.label_100.setObjectName("label_100")
        self.label_101 = QtWidgets.QLabel(self.page_7)
        self.label_101.setGeometry(QtCore.QRect(580, 380, 231, 31))
        self.label_101.setStyleSheet("background-color: white;")
        self.label_101.setText("")
        self.label_101.setObjectName("label_101")
        self.pushButton_20 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_20.setGeometry(QtCore.QRect(940, 240, 111, 41))
        self.pushButton_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_20.setStyleSheet("background-color: silver;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_21.setGeometry(QtCore.QRect(940, 690, 111, 41))
        self.pushButton_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_21.setStyleSheet("background-color: silver;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"")
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_102 = QtWidgets.QLabel(self.page_7)
        self.label_102.setGeometry(QtCore.QRect(580, 530, 231, 31))
        self.label_102.setStyleSheet("background-color: white;")
        self.label_102.setText("")
        self.label_102.setObjectName("label_102")
        self.label_103 = QtWidgets.QLabel(self.page_7)
        self.label_103.setGeometry(QtCore.QRect(600, 70, 211, 61))
        self.label_103.setStyleSheet("\n"
"font-size:40px;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"")
        self.label_103.setObjectName("label_103")
        self.label_104 = QtWidgets.QLabel(self.page_7)
        self.label_104.setGeometry(QtCore.QRect(340, 530, 81, 71))
        self.label_104.setText("")
        self.label_104.setPixmap(QtGui.QPixmap("../Fulls/fotos/icono3.png"))
        self.label_104.setScaledContents(True)
        self.label_104.setObjectName("label_104")
        self.pushButton_22 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_22.setGeometry(QtCore.QRect(940, 390, 111, 41))
        self.pushButton_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_22.setStyleSheet("background-color: silver;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_23.setGeometry(QtCore.QRect(20, 30, 181, 61))
        self.pushButton_23.setStyleSheet("#pushButton_23 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: black;\n"
"border-style: solid;\n"
" color: white;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_24.setGeometry(QtCore.QRect(20, 260, 181, 61))
        self.pushButton_24.setStyleSheet("#pushButton_24 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #99FF99;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.label_105 = QtWidgets.QLabel(self.page_7)
        self.label_105.setGeometry(QtCore.QRect(270, 640, 856, 5))
        self.label_105.setStyleSheet("background-color: black;")
        self.label_105.setObjectName("label_105")
        self.stackedWidget.addWidget(self.page_7)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_28 = QtWidgets.QLabel(self.page_5)
        self.label_28.setGeometry(QtCore.QRect(940, 530, 101, 21))
        self.label_28.setStyleSheet("font-size: 15px;")
        self.label_28.setObjectName("label_28")
        self.label_23 = QtWidgets.QLabel(self.page_5)
        self.label_23.setGeometry(QtCore.QRect(940, 300, 101, 21))
        self.label_23.setStyleSheet("font-size: 15px;")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.page_5)
        self.label_25.setGeometry(QtCore.QRect(940, 400, 101, 21))
        self.label_25.setStyleSheet("font-size: 15px;")
        self.label_25.setObjectName("label_25")
        self.label_27 = QtWidgets.QLabel(self.page_5)
        self.label_27.setGeometry(QtCore.QRect(940, 500, 101, 21))
        self.label_27.setStyleSheet("font-size: 15px;")
        self.label_27.setObjectName("label_27")
        self.label_11 = QtWidgets.QLabel(self.page_5)
        self.label_11.setGeometry(QtCore.QRect(900, 630, 31, 31))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../Fulls/fotos/logoTw.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(self.page_5)
        self.label_14.setGeometry(QtCore.QRect(680, 290, 101, 21))
        self.label_14.setStyleSheet("font-size: 15px;")
        self.label_14.setObjectName("label_14")
        self.label_12 = QtWidgets.QLabel(self.page_5)
        self.label_12.setGeometry(QtCore.QRect(680, 200, 101, 21))
        self.label_12.setStyleSheet("font-size: 15px;")
        self.label_12.setObjectName("label_12")
        self.label_18 = QtWidgets.QLabel(self.page_5)
        self.label_18.setGeometry(QtCore.QRect(680, 500, 101, 21))
        self.label_18.setStyleSheet("font-size: 15px;")
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.page_5)
        self.label_20.setGeometry(QtCore.QRect(680, 610, 201, 21))
        self.label_20.setStyleSheet("font-size: 15px;")
        self.label_20.setObjectName("label_20")
        self.label_13 = QtWidgets.QLabel(self.page_5)
        self.label_13.setGeometry(QtCore.QRect(680, 230, 101, 21))
        self.label_13.setStyleSheet("font-size: 15px;")
        self.label_13.setObjectName("label_13")
        self.label_7 = QtWidgets.QLabel(self.page_5)
        self.label_7.setGeometry(QtCore.QRect(895, 210, 41, 21))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../Fulls/fotos/logoins.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_30 = QtWidgets.QLabel(self.page_5)
        self.label_30.setGeometry(QtCore.QRect(940, 630, 121, 21))
        self.label_30.setStyleSheet("font-size: 15px;")
        self.label_30.setObjectName("label_30")
        self.label_8 = QtWidgets.QLabel(self.page_5)
        self.label_8.setGeometry(QtCore.QRect(895, 500, 41, 21))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../Fulls/fotos/logoins.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_16 = QtWidgets.QLabel(self.page_5)
        self.label_16.setGeometry(QtCore.QRect(680, 390, 121, 21))
        self.label_16.setStyleSheet("font-size: 15px;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_5)
        self.label_17.setGeometry(QtCore.QRect(680, 420, 101, 21))
        self.label_17.setStyleSheet("font-size: 15px;")
        self.label_17.setObjectName("label_17")
        self.label_21 = QtWidgets.QLabel(self.page_5)
        self.label_21.setGeometry(QtCore.QRect(940, 210, 101, 21))
        self.label_21.setStyleSheet("font-size: 15px;")
        self.label_21.setObjectName("label_21")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 180, 181, 61))
        self.pushButton_5.setStyleSheet("#pushButton_5 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #FF6666;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_9 = QtWidgets.QLabel(self.page_5)
        self.label_9.setGeometry(QtCore.QRect(900, 330, 31, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../Fulls/fotos/logoTw.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.page_5)
        self.label_10.setGeometry(QtCore.QRect(900, 240, 31, 31))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../Fulls/fotos/logoTw.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_15 = QtWidgets.QLabel(self.page_5)
        self.label_15.setGeometry(QtCore.QRect(895, 400, 41, 21))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../Fulls/fotos/logoins.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_19 = QtWidgets.QLabel(self.page_5)
        self.label_19.setGeometry(QtCore.QRect(900, 430, 31, 31))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("../Fulls/fotos/logoTw.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_22 = QtWidgets.QLabel(self.page_5)
        self.label_22.setGeometry(QtCore.QRect(940, 240, 101, 21))
        self.label_22.setStyleSheet("font-size: 15px;")
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.page_5)
        self.label_24.setGeometry(QtCore.QRect(680, 530, 151, 21))
        self.label_24.setStyleSheet("font-size: 15px;")
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(self.page_5)
        self.label_26.setGeometry(QtCore.QRect(610, 60, 211, 61))
        self.label_26.setStyleSheet("#label_26 {\n"
"font-size:40px;\n"
"\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"\n"
"}")
        self.label_26.setObjectName("label_26")
        self.label_29 = QtWidgets.QLabel(self.page_5)
        self.label_29.setGeometry(QtCore.QRect(895, 600, 41, 21))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("../Fulls/fotos/logoins.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 20, 181, 61))
        self.pushButton_6.setStyleSheet("#pushButton_6 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: black;\n"
"border-style: solid;\n"
" color: white;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_31 = QtWidgets.QLabel(self.page_5)
        self.label_31.setGeometry(QtCore.QRect(895, 300, 41, 21))
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("../Fulls/fotos/logoins.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.tableWidget = QtWidgets.QTableWidget(self.page_5)
        self.tableWidget.setGeometry(QtCore.QRect(230, 130, 881, 551))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setSizeIncrement(QtCore.QSize(60, 0))
        self.tableWidget.setBaseSize(QtCore.QSize(20, 30))
        self.tableWidget.setStyleSheet("#tableWidget {\n"
"background-color: #FFCC99;\n"
"border: 5px solid black;\n"
"}")
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 204, 153))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(215)
        self.tableWidget.verticalHeader().setDefaultSectionSize(100)
        self.tableWidget.verticalHeader().setMinimumSectionSize(16)
        self.label_32 = QtWidgets.QLabel(self.page_5)
        self.label_32.setGeometry(QtCore.QRect(940, 600, 121, 21))
        self.label_32.setStyleSheet("font-size: 15px;")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.page_5)
        self.label_33.setGeometry(QtCore.QRect(900, 530, 31, 31))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("../Fulls/fotos/logoTw.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 250, 181, 61))
        self.pushButton_7.setStyleSheet("#pushButton_7 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #99FF99;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_34 = QtWidgets.QLabel(self.page_5)
        self.label_34.setGeometry(QtCore.QRect(940, 330, 101, 21))
        self.label_34.setStyleSheet("font-size: 15px;")
        self.label_34.setObjectName("label_34")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 320, 181, 61))
        self.pushButton_8.setStyleSheet("#pushButton_8 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #66CCCC;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_35 = QtWidgets.QLabel(self.page_5)
        self.label_35.setGeometry(QtCore.QRect(940, 430, 101, 21))
        self.label_35.setStyleSheet("font-size: 15px;")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.page_5)
        self.label_36.setGeometry(QtCore.QRect(680, 320, 151, 21))
        self.label_36.setStyleSheet("font-size: 15px;")
        self.label_36.setObjectName("label_36")
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.tableWidget.raise_()
        self.label_33.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_24.raise_()
        self.label_26.raise_()
        self.label_25.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.label_34.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_23.raise_()
        self.stackedWidget.addWidget(self.page_5)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_37 = QtWidgets.QLabel(self.page_4)
        self.label_37.setGeometry(QtCore.QRect(890, 350, 31, 21))
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.page_4)
        self.label_38.setGeometry(QtCore.QRect(891, 650, 31, 21))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.page_4)
        self.label_39.setGeometry(QtCore.QRect(521, 80, 241, 61))
        self.label_39.setStyleSheet("#label_39 {\n"
"font-size:40px;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"\n"
"}")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.page_4)
        self.label_40.setGeometry(QtCore.QRect(812, 550, 31, 21))
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.page_4)
        self.label_41.setGeometry(QtCore.QRect(850, 350, 31, 21))
        self.label_41.setText("")
        self.label_41.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_41.setScaledContents(True)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.page_4)
        self.label_42.setGeometry(QtCore.QRect(851, 450, 31, 21))
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.page_4)
        self.label_43.setGeometry(QtCore.QRect(772, 450, 31, 21))
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.page_4)
        self.label_44.setGeometry(QtCore.QRect(772, 550, 31, 21))
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_44.setScaledContents(True)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.page_4)
        self.label_45.setGeometry(QtCore.QRect(891, 450, 31, 21))
        self.label_45.setText("")
        self.label_45.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_45.setScaledContents(True)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.page_4)
        self.label_46.setGeometry(QtCore.QRect(932, 450, 31, 21))
        self.label_46.setText("")
        self.label_46.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.page_4)
        self.label_47.setGeometry(QtCore.QRect(851, 650, 31, 21))
        self.label_47.setText("")
        self.label_47.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_47.setScaledContents(True)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.page_4)
        self.label_48.setGeometry(QtCore.QRect(932, 550, 31, 21))
        self.label_48.setText("")
        self.label_48.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName("label_48")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_9.setGeometry(QtCore.QRect(21, 20, 181, 61))
        self.pushButton_9.setStyleSheet("#pushButton_9 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: black;\n"
"border-style: solid;\n"
" color: white;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_49 = QtWidgets.QLabel(self.page_4)
        self.label_49.setGeometry(QtCore.QRect(581, 320, 71, 91))
        self.label_49.setText("")
        self.label_49.setPixmap(QtGui.QPixmap("../Fulls/fotos/rapero1.png"))
        self.label_49.setScaledContents(True)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.page_4)
        self.label_50.setGeometry(QtCore.QRect(932, 650, 31, 21))
        self.label_50.setText("")
        self.label_50.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName("label_50")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_4)
        self.tableWidget_2.setGeometry(QtCore.QRect(241, 170, 761, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget_2.setSizeIncrement(QtCore.QSize(60, 0))
        self.tableWidget_2.setBaseSize(QtCore.QSize(20, 30))
        self.tableWidget_2.setStyleSheet("#tableWidget_2 {\n"
"background-color: #FFCC99;\n"
"border: 5px solid black;\n"
"}")
        self.tableWidget_2.setAutoScroll(True)
        self.tableWidget_2.setAutoScrollMargin(16)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 204, 153))
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setItem(4, 0, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(100)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(16)
        self.label_51 = QtWidgets.QLabel(self.page_4)
        self.label_51.setGeometry(QtCore.QRect(891, 250, 31, 21))
        self.label_51.setText("")
        self.label_51.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_51.setScaledContents(True)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.page_4)
        self.label_52.setGeometry(QtCore.QRect(581, 520, 81, 91))
        self.label_52.setText("")
        self.label_52.setPixmap(QtGui.QPixmap("../Fulls/fotos/rapero3.png"))
        self.label_52.setScaledContents(True)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.page_4)
        self.label_53.setGeometry(QtCore.QRect(581, 220, 61, 91))
        self.label_53.setText("")
        self.label_53.setPixmap(QtGui.QPixmap("../Fulls/fotos/rapero5.png"))
        self.label_53.setScaledContents(True)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.page_4)
        self.label_54.setGeometry(QtCore.QRect(932, 250, 31, 21))
        self.label_54.setText("")
        self.label_54.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_54.setScaledContents(True)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.page_4)
        self.label_55.setGeometry(QtCore.QRect(891, 550, 31, 21))
        self.label_55.setText("")
        self.label_55.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_55.setScaledContents(True)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.page_4)
        self.label_56.setGeometry(QtCore.QRect(851, 550, 31, 21))
        self.label_56.setText("")
        self.label_56.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.page_4)
        self.label_57.setGeometry(QtCore.QRect(811, 350, 31, 21))
        self.label_57.setText("")
        self.label_57.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_57.setScaledContents(True)
        self.label_57.setObjectName("label_57")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_10.setGeometry(QtCore.QRect(21, 320, 181, 61))
        self.pushButton_10.setStyleSheet("#pushButton_10 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #66CCCC;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_58 = QtWidgets.QLabel(self.page_4)
        self.label_58.setGeometry(QtCore.QRect(812, 450, 31, 21))
        self.label_58.setText("")
        self.label_58.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_58.setScaledContents(True)
        self.label_58.setObjectName("label_58")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_11.setGeometry(QtCore.QRect(21, 250, 181, 61))
        self.pushButton_11.setStyleSheet("#pushButton_11 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #99FF99;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_59 = QtWidgets.QLabel(self.page_4)
        self.label_59.setGeometry(QtCore.QRect(772, 650, 31, 21))
        self.label_59.setText("")
        self.label_59.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_59.setScaledContents(True)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.page_4)
        self.label_60.setGeometry(QtCore.QRect(812, 250, 31, 21))
        self.label_60.setText("")
        self.label_60.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_60.setScaledContents(True)
        self.label_60.setObjectName("label_60")
        self.pushButton_12 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_12.setGeometry(QtCore.QRect(21, 180, 181, 61))
        self.pushButton_12.setStyleSheet("#pushButton_12 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #FFCC00;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_61 = QtWidgets.QLabel(self.page_4)
        self.label_61.setGeometry(QtCore.QRect(581, 420, 91, 91))
        self.label_61.setText("")
        self.label_61.setPixmap(QtGui.QPixmap("../Fulls/fotos/rapero2.png"))
        self.label_61.setScaledContents(True)
        self.label_61.setWordWrap(False)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.page_4)
        self.label_62.setGeometry(QtCore.QRect(772, 350, 31, 21))
        self.label_62.setText("")
        self.label_62.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_62.setScaledContents(True)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.page_4)
        self.label_63.setGeometry(QtCore.QRect(851, 250, 31, 21))
        self.label_63.setText("")
        self.label_63.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_63.setScaledContents(True)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.page_4)
        self.label_64.setGeometry(QtCore.QRect(931, 350, 31, 21))
        self.label_64.setText("")
        self.label_64.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_64.setScaledContents(True)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.page_4)
        self.label_65.setGeometry(QtCore.QRect(591, 620, 81, 91))
        self.label_65.setText("")
        self.label_65.setPixmap(QtGui.QPixmap("../Fulls/fotos/rapero4.png"))
        self.label_65.setScaledContents(True)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.page_4)
        self.label_66.setGeometry(QtCore.QRect(772, 250, 31, 21))
        self.label_66.setText("")
        self.label_66.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_66.setScaledContents(True)
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.page_4)
        self.label_67.setGeometry(QtCore.QRect(812, 650, 31, 21))
        self.label_67.setText("")
        self.label_67.setPixmap(QtGui.QPixmap("../star-300x300.png"))
        self.label_67.setScaledContents(True)
        self.label_67.setObjectName("label_67")
        self.label_39.raise_()
        self.pushButton_9.raise_()
        self.tableWidget_2.raise_()
        self.label_51.raise_()
        self.label_52.raise_()
        self.label_53.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.label_61.raise_()
        self.label_62.raise_()
        self.label_63.raise_()
        self.label_64.raise_()
        self.label_65.raise_()
        self.label_66.raise_()
        self.label_67.raise_()
        self.label_49.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.label_56.raise_()
        self.label_58.raise_()
        self.label_59.raise_()
        self.label_60.raise_()
        self.label_57.raise_()
        self.label_50.raise_()
        self.label_48.raise_()
        self.label_47.raise_()
        self.label_46.raise_()
        self.label_45.raise_()
        self.label_44.raise_()
        self.label_43.raise_()
        self.label_42.raise_()
        self.label_41.raise_()
        self.label_40.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.stackedWidget.addWidget(self.page_4)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_68 = QtWidgets.QLabel(self.page_6)
        self.label_68.setGeometry(QtCore.QRect(807, 270, 51, 91))
        self.label_68.setStyleSheet("background-color:none;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 200;\n"
"font-size: 13px;\n"
"font-weight: 500;\n"
"")
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.page_6)
        self.label_69.setGeometry(QtCore.QRect(520, 150, 371, 31))
        self.label_69.setStyleSheet("background-color:none;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 13px")
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.page_6)
        self.label_70.setGeometry(QtCore.QRect(510, 190, 391, 4))
        self.label_70.setStyleSheet("background-color:black;")
        self.label_70.setObjectName("label_70")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_13.setGeometry(QtCore.QRect(30, 260, 181, 61))
        self.pushButton_13.setStyleSheet("#pushButton_13 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #FFCC00;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_71 = QtWidgets.QLabel(self.page_6)
        self.label_71.setGeometry(QtCore.QRect(520, 510, 361, 31))
        self.label_71.setStyleSheet("background-color:none;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 200;\n"
"font-size: 13px")
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.page_6)
        self.label_72.setGeometry(QtCore.QRect(510, 490, 391, 4))
        self.label_72.setStyleSheet("background-color:black;")
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.page_6)
        self.label_73.setGeometry(QtCore.QRect(320, 140, 581, 231))
        self.label_73.setStyleSheet("#label_73 {\n"
"border: 5px solid black;\n"
"background-color:#E0DDDB;\n"
"}")
        self.label_73.setText("")
        self.label_73.setObjectName("label_73")
        self.pushButton_14 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_14.setGeometry(QtCore.QRect(30, 330, 181, 61))
        self.pushButton_14.setStyleSheet("#pushButton_14 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: #66CCCC;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"}\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_74 = QtWidgets.QLabel(self.page_6)
        self.label_74.setGeometry(QtCore.QRect(470, 50, 311, 71))
        self.label_74.setStyleSheet("font-size: 25px;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 35px;\n"
"background-color: none;")
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.page_6)
        self.label_75.setGeometry(QtCore.QRect(530, 450, 371, 31))
        self.label_75.setStyleSheet("background-color:none;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 13px")
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.page_6)
        self.label_76.setGeometry(QtCore.QRect(520, 560, 371, 81))
        self.label_76.setStyleSheet("background-color:none;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 500;\n"
"font-size: 13px;\n"
"")
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.page_6)
        self.label_77.setGeometry(QtCore.QRect(520, 240, 161, 31))
        self.label_77.setStyleSheet("background-color:none;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 200;\n"
"font-size: 13px")
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.page_6)
        self.label_78.setGeometry(QtCore.QRect(320, 160, 191, 181))
        self.label_78.setStyleSheet("background-color: none")
        self.label_78.setText("")
        self.label_78.setPixmap(QtGui.QPixmap("../Fulls/fotos/noticia1.png"))
        self.label_78.setScaledContents(True)
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.page_6)
        self.label_79.setGeometry(QtCore.QRect(720, 270, 51, 91))
        self.label_79.setStyleSheet("background-color:none;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 200;\n"
"font-size: 13px;\n"
"font-weight: 500;\n"
"")
        self.label_79.setObjectName("label_79")
        self.pushButton_15 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_15.setGeometry(QtCore.QRect(30, 30, 181, 61))
        self.pushButton_15.setStyleSheet("#pushButton_15 {\n"
"border-color: black;\n"
"border-width: 4px;\n"
"background-color: black;\n"
"border-style: solid;\n"
" color: white;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_16.setGeometry(QtCore.QRect(30, 190, 181, 61))
        self.pushButton_16.setStyleSheet("#pushButton_16 {\n"
"border-color: black;\n""border-width: 4px;\n"
"background-color: #FF6666;\n"
"border-style: solid;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 700;\n"
"font-size: 15px;\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_80 = QtWidgets.QLabel(self.page_6)
        self.label_80.setGeometry(QtCore.QRect(520, 540, 71, 21))
        self.label_80.setStyleSheet("background-color:none;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 200;\n"
"font-size: 13px")
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.page_6)
        self.label_81.setGeometry(QtCore.QRect(520, 210, 371, 31))
        self.label_81.setStyleSheet("background-color:none;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 200;\n"
"font-size: 13px")
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.page_6)
        self.label_82.setGeometry(QtCore.QRect(633, 270, 51, 91))
        self.label_82.setStyleSheet("background-color:none;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 200;\n"
"font-size: 13px;\n"
"font-weight: 500;\n"
"")
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.page_6)
        self.label_83.setGeometry(QtCore.QRect(320, 440, 581, 231))
        self.label_83.setStyleSheet("border: 5px solid black;\n"
"background-color:#E0DDDB;")
        self.label_83.setText("")
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.page_6)
        self.label_84.setGeometry(QtCore.QRect(349, 484, 141, 141))
        self.label_84.setStyleSheet("background-color:none;")
        self.label_84.setText("")
        self.label_84.setPixmap(QtGui.QPixmap("../Fulls/fotos/noticia2.png"))
        self.label_84.setScaledContents(True)
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.page_6)
        self.label_85.setGeometry(QtCore.QRect(510, 140, 4, 231))
        self.label_85.setStyleSheet("background-color:black;")
        self.label_85.setText("")
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.page_6)
        self.label_86.setGeometry(QtCore.QRect(510, 440, 4, 231))
        self.label_86.setStyleSheet("background-color:black;")
        self.label_86.setText("")
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.page_6)
        self.label_87.setGeometry(QtCore.QRect(544, 270, 41, 91))
        self.label_87.setStyleSheet("background-color:none;\n"
"font-family: \"Comic Sans MS\", cursive, sans-serif;\n"
"font-weight: 500;\n"
"font-size: 13px")
        self.label_87.setObjectName("label_87")
        self.pushButton_13.raise_()
        self.label_73.raise_()
        self.pushButton_14.raise_()
        self.label_74.raise_()
        self.label_77.raise_()
        self.label_78.raise_()
        self.label_79.raise_()
        self.pushButton_15.raise_()
        self.pushButton_16.raise_()
        self.label_81.raise_()
        self.label_82.raise_()
        self.label_83.raise_()
        self.label_84.raise_()
        self.label_85.raise_()
        self.label_86.raise_()
        self.label_87.raise_()
        self.label_75.raise_()
        self.label_76.raise_()
        self.label_80.raise_()
        self.label_68.raise_()
        self.label_69.raise_()
        self.label_70.raise_()
        self.label_71.raise_()
        self.label_72.raise_()
        self.stackedWidget.addWidget(self.page_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "NOTÍCIAS"))
        self.pushButton_2.setText(_translate("MainWindow", "TOP RAPEROS"))
        self.pushButton_3.setText(_translate("MainWindow", "INSCRIPCIONES"))
        self.pushButton.setText(_translate("MainWindow", "RANKING"))
        self.pushButton_17.setText(_translate("MainWindow", "Top raperos"))
        self.label_88.setText(_translate("MainWindow", "TextLabel"))
        self.label_92.setText(_translate("MainWindow", "TextLabel"))
        self.label_95.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_18.setText(_translate("MainWindow", "Inscribirse"))
        self.pushButton_19.setText(_translate("MainWindow", "Ranking"))
        self.label_100.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_20.setText(_translate("MainWindow", "Inscribirse"))
        self.pushButton_21.setText(_translate("MainWindow", "Inscribirse"))
        self.label_103.setText(_translate("MainWindow", "Inscripción"))
        self.pushButton_22.setText(_translate("MainWindow", "Inscribirse"))
        self.pushButton_23.setText(_translate("MainWindow", "Volver"))
        self.pushButton_24.setText(_translate("MainWindow", "Notícias"))
        self.label_105.setText(_translate("MainWindow", "TextLabel"))
        #self.label_28.setText(_translate("MainWindow", "@sarasocass"))
        #self.label_25.setText(_translate("MainWindow", "@handerwk"))
        #self.label_27.setText(_translate("MainWindow", "@socasmc"))
        self.label_14.setText(_translate("MainWindow", "Kingsize (8000)"))
        self.label_12.setText(_translate("MainWindow", "RedBull (8000)"))
        self.label_18.setText(_translate("MainWindow", "RedBull (8000)"))
        self.label_20.setText(_translate("MainWindow", "Dragones del freestyle (1500)"))
        self.label_13.setText(_translate("MainWindow", "BDM (700)"))
        #self.label_30.setText(_translate("MainWindow", "@diegobottamino"))
        self.label_16.setText(_translate("MainWindow", "Gold battle (8000)"))
        self.label_17.setText(_translate("MainWindow", "BDM (700)"))
        #self.label_21.setText(_translate("MainWindow", "@nachosrk"))
        self.pushButton_5.setText(_translate("MainWindow", "Top raperos"))
        #self.label_22.setText(_translate("MainWindow", "@nachosrk "))
        self.label_24.setText(_translate("MainWindow", "Street Warriors (100)"))
        self.label_26.setText(_translate("MainWindow", "Ranking"))
        self.pushButton_6.setText(_translate("MainWindow", "Volver"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Puntos"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Camp ganados"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Redes"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "SKR"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "8700 pts"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Jesus LC"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "7200 pts"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Hander"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "5500 pts"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Sara socas"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "2100 pts"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Botta"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "1500 pts"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        #self.label_32.setText(_translate("MainWindow", "@diegoottamino"))
        self.pushButton_7.setText(_translate("MainWindow", "Notícias"))
        #self.label_34.setText(_translate("MainWindow", "@jessuslc"))
        self.pushButton_8.setText(_translate("MainWindow", "Inscripciones"))
        #self.label_35.setText(_translate("MainWindow", "@hander_wk "))
        self.label_36.setText(_translate("MainWindow", "Supremacia MC (700)"))
        self.label_39.setText(_translate("MainWindow", "Top raperos"))
        self.pushButton_9.setText(_translate("MainWindow", "Volver"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Imagen"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Rating"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("MainWindow", "Trueno"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("MainWindow", "Bnet"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("MainWindow", "Chuty"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("MainWindow", "Aczino"))
        item = self.tableWidget_2.item(4, 0)
        item.setText(_translate("MainWindow", "Skone"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton_10.setText(_translate("MainWindow", "Inscripciones"))
        self.pushButton_11.setText(_translate("MainWindow", "Notícias"))
        self.pushButton_12.setText(_translate("MainWindow", "Ranking"))
        self.label_68.setText(_translate("MainWindow", "Brasita\n"
"Tiago\n"
"MP\n"
"Kusa"))
        self.label_69.setText(_translate("MainWindow", "SELECCIONADOS REDBULL ARGENTINA 2020"))
        self.label_70.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_13.setText(_translate("MainWindow", "Ranking"))
        self.label_71.setText(_translate("MainWindow", "La última jornada de la FMS España nos dejó los siguientes "))
        self.label_72.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_14.setText(_translate("MainWindow", "Inscripciones"))
        self.label_74.setText(_translate("MainWindow", "Notícias"))
        self.label_75.setText(_translate("MainWindow", "RESULTADOS FMS España JORNADA 5"))
        self.label_76.setText(_translate("MainWindow", "Mister Ego ganó a Vivi SIN RÉPLICA\n"
"Gazir ganó a Sweet Pain CON RÉPLICA\n"
"Tirpa ganó Jesus LC SIN RÉPLICA\n"
"Zasko ganó a Blon CON RÉPLICA"))
        self.label_77.setText(_translate("MainWindow", "- - - PARTICIPANTES - - -"))
        self.label_79.setText(_translate("MainWindow", "Mecha\n"
"Klan\n"
"Tata\n"
"Nacho"))
        self.pushButton_15.setText(_translate("MainWindow", "Volver"))
        self.pushButton_16.setText(_translate("MainWindow", "Top raperos"))
        self.label_80.setText(_translate("MainWindow", "resultados:"))
        self.label_81.setText(_translate("MainWindow", "Ya disponemos de la lista oficial de Red Bull Argentina 2020"))
        self.label_82.setText(_translate("MainWindow", "Zaina\n"
"Stuart\n"
"Dani\n"
"Sub"))
        self.label_87.setText(_translate("MainWindow", "Wolf\n"
"Roma\n"
"Acru\n"
"Cacha"))

        self.label_27.setText('<a href="https://www.instagram.com/sarasocass/" style=\"text-decoration:none; color:black;\">@sarasocass</a>')
        self.label_27.setOpenExternalLinks(True)
        self.label_28.setText('<a href="https://twitter.com/socasmc?lang=ca" style=\"text-decoration:none; color:black;\">@socasmc</a>')
        self.label_28.setOpenExternalLinks(True)
        self.label_32.setText('<a href="https://www.instagram.com/diegobottamino/" style=\"text-decoration:none; color:black;\">@diegobottamino</a>')
        self.label_32.setOpenExternalLinks(True)
        self.label_30.setText('<a href="https://twitter.com/diegobottamino" style=\"text-decoration:none; color:black;\">@diegobottamino</a>')
        self.label_30.setOpenExternalLinks(True)
        self.label_25.setText('<a href="https://www.instagram.com/hander_wk/" style=\"text-decoration:none; color:black;\">@hander_wk</a>')
        self.label_25.setOpenExternalLinks(True)
        self.label_35.setText('<a href="https://twitter.com/handerwk?lang=ca" style=\"text-decoration:none; color:black;\">@handerwk</a>')
        self.label_35.setOpenExternalLinks(True)
        self.label_34.setText('<a href="https://twitter.com/jesuuslc" style=\"text-decoration:none; color:black;\">@jesuuslc</a>')
        self.label_34.setOpenExternalLinks(True)
        self.label_22.setText('<a href="https://twitter.com/nachosrk" style=\"text-decoration:none; color:black;\">@nachosrk</a>')
        self.label_22.setOpenExternalLinks(True)
        self.label_21.setText('<a href="https://www.instagram.com/nachosrk/" style=\"text-decoration:none; color:black;\">@nachosrk</a>')
        self.label_21.setOpenExternalLinks(True)
		
    def botonera(self, boton):
        if (boton == 1):
            self.stackedWidget.setCurrentWidget(self.page_5)
            logging.info('Has ido a Ranking')
        if (boton == 2):
            self.stackedWidget.setCurrentWidget(self.page_4)
            logging.info('Has ido a Top raperos')
        if (boton == 3):
            self.stackedWidget.setCurrentWidget(self.page_7)
            logging.info('Has ido a Inscripciones')
        if (boton == 4):
            self.stackedWidget.setCurrentWidget(self.page_6)
            logging.info('Has ido a Notícias')


			
			
if __name__ == "__main__":

    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.pushButton.clicked.connect(lambda: ui.botonera(1))
    ui.pushButton_2.clicked.connect(lambda: ui.botonera(2))
    ui.pushButton_3.clicked.connect(lambda: ui.botonera(3))
    ui.pushButton_4.clicked.connect(lambda: ui.botonera(4))
    ui.pushButton_4.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_6)) 
    ui.pushButton_5.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_4))
    ui.pushButton_7.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_6))
    ui.pushButton_6.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_3)) 
    ui.pushButton_8.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_7)) 
    ui.pushButton_10.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_7))
    ui.pushButton_11.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_6))
    ui.pushButton_12.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_5))
    ui.pushButton_9.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_3))
    ui.pushButton_13.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_5))
    ui.pushButton_14.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_7))
    ui.pushButton_15.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_3))
    ui.pushButton_16.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_4))
    ui.pushButton_17.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_4))
    ui.pushButton_19.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_5))
    ui.pushButton_23.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_3))
    #ui.pushButton_.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_10))
    #ui.pushButton_26.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_4))
    #ui.pushButton_27.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_4))
    #ui.pushButton_28.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_4))
    #ui.pushButton_29.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_4))
    #ui.pushButton_30.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_10))
    #ui.label_49.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_2))
    #ui.label_61.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_8))
    #ui.label_52.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page))
    #ui.label_65.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.page_9)) 
	
	
    
    sys.exit(app.exec_())
